apiVersion: v1
kind: Service
metadata:
  name: k8-sample-flask-celery
  labels:
    app: k8-sample-flask-celery
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: k8-sample-flask-celery